name: py3.8
channels:
  - pytorch3d
  - fvcore
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.2.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - async-lru=2.0.4=py38h06a4308_0
  - attrs=24.2.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.1=heb4867d_0
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - cyrus-sasl=2.1.28=h52b45da_1
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20210915=py38
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py38h06a4308_0
  - httpcore=1.0.2=py38h06a4308_0
  - httpx=0.27.0=py38h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.10=pyhd8ed1ab_0
  - ipykernel=6.29.5=py38h06a4308_0
  - jedi=0.19.1=py38h06a4308_0
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38h06a4308_0
  - jupyter=1.0.0=py38h06a4308_9
  - jupyter-lsp=2.2.0=py38h06a4308_0
  - jupyter_console=6.6.3=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - jupyter_events=0.10.0=py38h06a4308_0
  - jupyter_server=2.14.1=py38h06a4308_0
  - jupyter_server_terminals=0.4.4=py38h06a4308_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38h06a4308_0
  - jupyterlab_widgets=3.0.10=py38h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnpp=11.8.0.86=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.16.4=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - notebook-shim=0.2.3=py38h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - overrides=7.4.0=py38h06a4308_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - ply=3.11=py38_0
  - portalocker=2.10.1=py38h578d9bd_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python-json-logger=2.0.7=py38h06a4308_0
  - python_abi=3.8=2_cp38
  - pytorch=2.1.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.8=py38_cu118_pyt210
  - pyzmq=25.1.2=py38h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.6.0=py38h06a4308_0
  - qtpy=2.4.1=py38h06a4308_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - rfc3339-validator=0.1.4=py38h06a4308_0
  - rfc3986-validator=0.1.1=py38h06a4308_0
  - send2trash=1.8.2=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=py38h06a4308_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.2=py38h06a4308_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.17.1=py38h06a4308_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.1.0=py38_cu118
  - torchtriton=2.1.0=py38
  - torchvision=0.16.0=py38_cu118
  - tornado=6.4.1=py38h5eee18b_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=py38h06a4308_0
  - urllib3=2.2.3=py38h06a4308_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38h06a4308_0
  - werkzeug=3.0.4=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - apptools==5.3.0
      - argcomplete==3.5.1
      - array-record==0.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - autocommand==2.2.2
      - av==12.3.0
      - av2==0.2.1
      - backports-tarfile==1.2.0
      - black==24.8.0
      - blessed==1.20.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - ccimport==0.4.3
      - cheroot==10.0.1
      - cherrypy==18.8.0
      - chumpy==0.70
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorlog==6.8.2
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.1.1
      - cumm-cu118==0.4.11
      - cycler==0.12.1
      - cython==3.0.11
      - dacite==1.8.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2023.3.1
      - dataclass-array==1.4.1
      - deprecation==2.1.0
      - descartes==1.1.0
      - dill==0.3.9
      - distlib==0.3.9
      - dm-tree==0.1.8
      - easydict==1.13
      - einops==0.8.0
      - einsum==0.3.0
      - entrypoints==0.4
      - envisage==7.0.3
      - etils==1.3.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filterpy==1.4.5
      - fire==0.7.0
      - flake8==7.1.1
      - flake8-bugbear==24.8.19
      - flake8-comprehensions==3.15.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - gast==0.4.0
      - google-auth==2.16.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.66.0
      - gpustat==1.1.1
      - grpcio==1.34.1
      - h5py==3.11.0
      - huggingface-hub==0.27.1
      - imageio==2.35.1
      - immutabledict==2.2.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaraco-collections==5.0.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jaraco-text==4.0.0
      - jax==0.4.13
      - joblib==1.4.2
      - jsonpointer==3.0.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==7.4.9
      - jupyter-packaging==0.12.3
      - jupyter-server-fileid==0.9.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-widgets==3.0.13
      - keras==2.12.0
      - kiwisolver==1.4.7
      - kornia==0.5.8
      - kornia-rs==0.1.5
      - labelcloud==1.1.1
      - lark==1.2.2
      - lazy-loader==0.4
      - lbs==0.2.3
      - libclang==18.1.1
      - libcst==1.1.0
      - littleutils==0.2.4
      - llvmlite==0.41.1
      - locket==1.0.0
      - lyft-dataset-sdk==0.0.8
      - markdown-it-py==3.0.0
      - matplotlib==3.6.1
      - mayavi==4.8.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - more-itertools==10.5.0
      - moreorless==0.4.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nbclassic==1.1.0
      - nbformat==5.7.0
      - ninja==1.11.1.1
      - notebook==6.5.7
      - nox==2024.10.9
      - numba==0.58.1
      - numpy==1.23.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.2.2
      - ogb==1.3.6
      - open3d==0.15.2
      - opencv-python==4.10.0.84
      - opendr==0.78
      - openexr==1.3.9
      - opt-einsum==3.4.0
      - optionaldict==0.1.2
      - outdated==0.2.2
      - pandas==1.5.3
      - parso==0.8.4
      - partd==1.4.1
      - pathspec==0.12.1
      - pccm==0.4.16
      - pexpect==4.9.0
      - pillow==9.2.0
      - pip==21.3.1
      - platformdirs==4.3.6
      - plotly==5.13.1
      - pluggy==1.5.0
      - pointnet==0.1.1
      - portend==3.2.0
      - promise==2.3
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==6.0.0
      - pure-eval==0.2.3
      - pyarrow==10.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pyface==8.0.0
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pyopengl==3.1.9
      - pyopengl-accelerate==3.1.9
      - pyparsing==3.0.9
      - pypcd-imp==0.1.5
      - pyproj==3.5.0
      - pyquaternion==0.9.9
      - pytest==8.3.3
      - python-lzf==0.2.6
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - quaternion==3.5.2.post4
      - referencing==0.35.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.9.2
      - rpds-py==0.20.0
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.0
      - setuptools==67.6.0
      - shapely==1.8.5.post1
      - sharedarray==3.2.4
      - spconv-cu118==2.3.6
      - stack-data==0.6.3
      - stdlibs==2024.10.25
      - taichi==1.7.2
      - tempora==5.7.1
      - tenacity==9.0.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.6.1
      - tensorboardx==2.4.1
      - tensorflow==2.12.0
      - tensorflow-addons==0.21.0
      - tensorflow-datasets==4.9.2
      - tensorflow-estimator==2.12.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.14.0
      - tensorflow-probability==0.19.0
      - tensorrt-cu11==10.5.0
      - tensorrt-cu11-bindings==10.5.0
      - tensorrt-cu11-libs==10.5.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.14
      - toml==0.10.2
      - tomli==2.0.2
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - trailrunner==1.4.0
      - traits==6.4.3
      - traitsui==8.0.0
      - trimesh==4.5.2
      - triton==3.0.0
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.1.1
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - usort==1.0.8.post1
      - version==0.1.0
      - virtualenv==20.26.6
      - visu3d==1.5.1
      - vtk==9.3.1
      - waymo-open-dataset-tf-2-12-0==1.6.4
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - wget==3.2
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - y-py==0.6.2
      - yarl==1.15.2
      - ypy-websocket==0.8.4
      - zc-lockfile==3.0.post1
prefix: /home/yizhi/anaconda3/envs/py3.8
